### ISSUE TITLE
[feature-request] Optional SmallCaps for the title

### ISSUE THREAD

**Issue by romen** [tvalimaki/beamertheme-tuni#2]
I'd like to add an option to the theme so that in the titlepage instead of the default

```latex
\usebeamerfont{title}\MakeUppercase{\inserttitle}\par
```
this is used instead:

```latex
\usebeamerfont{title}\textsc{\inserttitle}\par
```

I'd like for it to be an option as I believe it's highly subjective if SmallCaps are preferred or not, and also because it requires font support (the theme fonts seem to support it alright anyway).

I'm opening an issue instead of a PR because I don't know exactly how to approach this as a theme option.

**Comment by tvalimaki** [comment]
You're right that it's highly subjective. My subjective opinion is that SmallCaps don't fit the visual image of the presentation, so I'm inclined not to implement the feature. In addition, the graphic guidelines of TUNI do not use SmallCaps in their titles, and the idea of the style is to follow the guidelines as closely as possible.

I might change my mind if the request gets additional support, but for now I'm closing this.
