### ISSUE TITLE
Installation requires a lot of unnecessary dependencies

### ISSUE THREAD

**Issue by kubouch** [tvalimaki/beamertheme-tuni#5]
`make install` now requires building the example which requires a lot of dependencies. 

For example the example assumes people are using biber+biblatex which is not always the case (I had trouble installing biber and use bibtex). The same for other packages (such as filecontents which I've never used before since I put my bib entries in separate files).

**Comment by tvalimaki** [comment]
I myself use `biblatex` with `biber`, a combination that usually doesn't work that well with `beamer`. The example is to demonstrate that in this case, the combination actually _does_ work, so I won't remove them from the example. `filecontents` is just to have everything in the same source file, one would not use it in their own presentations, but, as you mention, have bib entries in a separate file. I could list the dependencies in the README to save the hassle of crawling through error messages.

Would it be better that `make install` would not build the example, but one would have to call `make example` or `make all` separately?

**Comment by kubouch** [comment]
I didn't know about `bibtex` not working in beamer. I ended up hand-typing them in footnotes since I have just a handful of them so I haven't even tried :-D.

`make install` should definitely **not** build the example - just enough stuff to generate the necessary files and put them to `$TEXMFHOME`. Running `make example` separately is very much less hassle than installing all the dependencies.

List of dependencies would help in any case.
